# declare a name for this job to be sample_job
#PBS -N allobjAdaptGrid_68k_100Rounds_2kcontig_8P_20Cores
# request a total of 40 processors for this job 
#   (2 nodes and 20 processors(core) per node)
#PBS -l nodes=8:ppn=20
# request 4 hours of wall clock time
#PBS -l walltime=1:00:00
# combine PBS standard output and error files
#PBS -j oe 
# mail is sent to you when the job starts and when it terminates or aborts
#PBS -m bea
# specify your email address 
#PBS -M satishpuri.dgp@gmail.com
module load geos
module load GCC/4.9.2-binutils-2.25
module load MPICH/3.1.4-GCC-4.9.2-binutils-2.25 
#change to the directory where you submitted the job 
cd /projects/dimos/mpiio/src
#include the full path to the name of your MPI program
#mpirun -np $PBS_NP /projects/dimos/mpiio/src/timing 2048 /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/roads25GB /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/cemetery
#mpirun -np $PBS_NP /projects/dimos/mpiio/src/timing 8192 /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/buildings /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/cemetery

#mpirun -np $PBS_NP /projects/dimos/mpiio/src/mpibinary

#mpirun -np $PBS_NP /projects/dimos/mpiio/src/filePartition/file

#mpirun -np 1 ./largeIO 10 /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/sample_road_network/road_network10k
#mpirun -np 1 ./largeIO 100 /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/road_networkdirectory/road_network

#mpirun -np $PBS_NP /projects/dimos/mpiio/src/filePartition/largeIO

#mpirun -np $PBS_NP /projects/dimos/mpiio/src/grid 8192 /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/allobjects /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/cemetery

mpirun -np $PBS_NP /projects/dimos/mpiio/src/allobj 28732 /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/lakes /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/cemetery

#mpirun -np $PBS_NP /projects/dimos/mpiio/src/adaptivegrid 68000 /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/buildings /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/cemetery
#mpirun -np $PBS_NP /projects/dimos/mpiio/src/allobj 68677 /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/allobjects /projects/dimos/GeoSpatial/data/SpatialHadoop_DataSets/cemetery
exit 0